### ISSUE TITLE
Clockwork throwing error on Lumen (Heroku hosted)

### ISSUE THREAD

**Issue by imjohnbon** [itsgoingd/clockwork#133]
I currently have a Lumen installation hosted on Heroku.

It works fine locally (on Homestead), but on Heroku Clockwork throws an error:

"FatalErrorException in /app/vendor/itsgoingd/clockwork/Clockwork/Support/CodeIgniter/Clockwork.php line 10: Class 'CI_Controller' not found"

It's very strange that it's trying to load a CodeIgniter file on a Lumen installation. Especially since I definitely have the correct Service Provider loading.

I've trying running composer dumpautoload, however the issue persists.

Any thoughts?

**Comment by itsgoingd** [comment]
Hey, looks like the same issue as https://github.com/itsgoingd/clockwork/issues/132.

Should be fixed in `1.11.2`, please try updating and re-deploying.

**Comment by imjohnbon** [comment]
Thanks for addressing this! I tried upgrading to 1.11.2 earlier and redeployed, however the same issue persisted. Dumped the autoload and cleared caching but still no dice.

Going to try again tomorrow.

**Comment by imjohnbon** [comment]
@itsgoingd Looks like it was just some caching issue on my end as I suspected it might be, because I tried it again tonight and now it works just fine. Thank you again!
